// Generated by CoffeeScript 1.8.0

/**
 * Get the no of users
 * @return {number} The size.
 */

(function() {
  var Admin, User, inherits;

  User = function() {};

  Admin = function() {};


  /**
   * Helper function that implements (pseudo)Classical inheritance inheritance.
   * @param {Function/Class} childClass
   * @param {Function/Class} parentClass
   */

  inherits = function(childClass, parentClass) {

    /** @constructor */
    var tempClass;
    tempClass = function() {};
    tempClass.prototype = parentClass.prototype;
    childClass.prototype = new tempClass;
    childClass.prototype.constructor = childClass;
  };

  User.prototype.getUsers = function() {};


  /**
   * Get access permission
   * @return {Boolean}
   */

  Admin.prototype.getAccess = function() {};


  /**
   * Get Roles
   * @return {collection} the roles
   */

  Admin.prototype.getRoles = function() {};

  inherits(Admin, User);

}).call(this);
